name: 'football_statsbomb'
version: '1.0.0'
config-version: 2

profile: 'football_statsbomb'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  football_statsbomb:
    marts:
      +materialized: table
