version: '3.8'

services:
  # Storage service (OSS)
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - dagnet

  mc:
    image: minio/mc:latest
    container_name: minio-client
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        sleep 5 && \
        mc alias set local http://minio:9000 minioadmin minioadmin && \
        mc mb -p local/football-statsbomb-data || true && \
        tail -f /dev/null
      "
    networks:
      - dagnet

  # Data Warehouse service (ClickHouse)
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9002:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_DB: football_statsbomb
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: admin
    command: 
      - /bin/sh
      - -c
      - |
        # Script d'initialisation
        echo "CREATE DATABASE IF NOT EXISTS football_statsbomb;" > /docker-entrypoint-initdb.d/init.sql
        /entrypoint.sh
    networks:
      - dagnet
  
  # DBT service
  dbt:
    image: ghcr.io/dbt-labs/dbt-core:1.5.0
    container_name: dbt
    volumes:
      - ./dbt:/usr/app/dbt  # Mount full dbt project
    working_dir: /usr/app/dbt
    environment:
      DBT_PROFILES_DIR: /usr/app/dbt/profiles
    networks:
      - dagnet
    tty: true
    stdin_open: true
    entrypoint: /bin/sh
    command: >
      -c "
        pip install dbt-clickhouse==1.5.1 && \
        tail -f /dev/null
      "

  # Orchestration service (Dagster)
  dagster:
    build:
      context: ./etl_pipeline
    image: mydagster:latest
    container_name: dagster
    ports:
      - "3000:3000"
    volumes:
      - ./etl_pipeline:/app
      - ./dbt:/app/dbt  # Mount full dbt project
    networks:
      - dagnet

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3001:3000"
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - metabase_data:/metabase-data
    networks:
      - dagnet

volumes:
  minio_data:
  clickhouse_data:
  metabase_data:

networks:
  dagnet:
